#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  debugButt,      sensorTouch)
#pragma config(Motor,  port1,           intake_lift,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ne_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           se_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           nw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           sw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shooter_left,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           shooter_right, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           manipulator,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intake_roller, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lift_right,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 0 = single joystick, 1 = double joystick
int controlMode = 0;

//void startLift(int speed){
//	startMotor(lift_left, speed);
//	startMotor(lift_right, speed*-1);
//}

//void stopLift(){
//	stopMotor(lift_left);
//	stopMotor(lift_right);
//}

void startIntakeShooter() {
	startMotor(intake_roller, -127);
	startMotor(intake_lift, -127);
	startMotor(shooter_left, 127);
	startMotor(shooter_right, -127);
}

void stopIntakeShooter() {
	stopMotor(intake_roller);
	stopMotor(intake_lift);
	stopMotor(shooter_left);
	stopMotor(shooter_right);
}

task main() {
	while(true){
		if (controlMode == 0) {
			motor[ne_motor] = -1 * (vexRT[Ch2] - vexRT[Ch1])/2;
			motor[se_motor] = -1 * (vexRT[Ch2] - vexRT[Ch1])/2;

			motor[nw_motor]= (vexRT[Ch2] + vexRT[Ch1])/2;
			motor[sw_motor] = (vexRT[Ch2] + vexRT[Ch1])/2;
		} else if (controlMode == 1) {
			motor[ne_motor] = -1 * vexRT[Ch2];
			motor[se_motor] = -1 * vexRT[Ch2];

			motor[nw_motor]= vexRT[Ch3];
			motor[sw_motor] = vexRT[Ch3];
		}

		//if (vexRT[Btn6U] == 1){
		//	startLift(127);
		//} else if (vexRT[Btn6D] ==  1) {
		//	startLift(-127);
		//} else {
		//	stopLift();
		//}

		if (vexRT[Btn8R] == 1 || SensorValue[debugButt]){
			startIntakeShooter();
		} else {
			stopIntakeShooter();
		}


		if (vexRT[Btn7L] == 1 && SensorValue[potentiometer] <= 2730) {
			startMotor(manipulator, 127);
		} else if (vexRT[Btn7D] == 1 && SensorValue[potentiometer] >= 0) {
			startMotor(manipulator, -127);
		} else {
			stopMotor(manipulator);
		}
	}
}
