#pragma config(Sensor, in1,    light,          sensorReflection)
#pragma config(Sensor, in4,    potent,         sensorPotentiometer)
#pragma config(Sensor, in6,    potent2,        sensorPotentiometer)
#pragma config(Sensor, in7,    line,           sensorLineFollower)
#pragma config(Motor,  port1,           motor1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		if (vexRT[Ch2] >= 100) {
			startMotor(motor1, 127);
		} else if (vexRT[Ch2] <= -100) {
			startMotor(motor1, -127);
		} else {
			stopMotor(motor1);
		}

		if (vexRT[Ch3] >= 100) {
			startMotor(servo, 127);
		} else if (vexRT[Ch3] <= -100){
			startMotor(servo, -127);
		} else {
			stopMotor(servo);
		}
	}
}
