#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  green,          sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int bleft = 1;
const int bmid = 2;
const int bright = 4;

string screens[3] = {"red", "yellow", "green"};
tSensors leds[3] = {red, yellow, green};
int current_screen = 0;

void displayScreen(int screen) {
	displayLCDCenteredString(0, screens[screen]);
	displayLCDCenteredString(1, " <     []     > ")
}

void switchLEDState(int led) {
	if (SensorValue[leds[led]] == 1) {
		turnLEDOff(leds[led]);
	}	else {
		turnLEDOn(leds[led]);
	}
}

void untilButtonRelease() {
	while (nLCDButtons != 0) {}
	return;
}

task buttonlisten() {
	while (true) {
		if (nLCDButtons == bleft) {
			untilButtonRelease();
			if (current_screen > 0) {
				current_screen--;
				displayScreen(current_screen);
			}
		} else if (nLCDButtons == bright) {
			untilButtonRelease();
			if (current_screen < 2) {
				current_screen++;
				displayScreen(current_screen);
			}
		} else if (nLCDButtons == bmid) {
			untilButtonRelease();
			switchLEDState(current_screen);
		}
		writeDebugStreamLine("%d", nLCDButtons)
	}
}

task main() {
	startTask(buttonlisten);

	displayScreen(0);
}
