#pragma config(Sensor, dgtl1,  butt,           sensorTouch)
#pragma config(Motor,  port1,           plunge,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          plunge1,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int plungespd = 127;

task main() {
	while (true) {
		if (SensorValue[butt] == 1) {
			motor[plunge] = -1 * plungespd;
			motor[plunge1] = plungespd;
		}	else {
			motor[plunge] = 0;
			motor[plunge1] = 0;
		}
	}
}
