#pragma config(Motor,  port4,           mot,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	startMotor(mot, 127);
	delay(5000);
	stopMotor(mot);
}
