#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           mright,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mleft,         tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// circ 12.566
// cell 24
// 1.9 rot
// 1200 ticks

const int defspeed = -127;
const float rotation = 627;
const float remnant = 250;
const float cell = 2.3;

void go(float rotations) {
	resetMotorEncoder(mleft);
	resetMotorEncoder(mright);

	int speed;
	int ticks = (rotations * rotation) - remnant;
	if (rotations < 0) {
		speed = defspeed * -1;
	} else {
		speed = defspeed;
	}

	while ((getMotorEncoder(mleft) >= -1 * ticks) && (getMotorEncoder(mright) <= ticks)) {
		motor[mleft] = speed;
		motor[mright] = -1 * speed;
	}
	motor[mleft] = 0;
	motor[mright] = 0;
}

task main() {
	go(2);
}
