#pragma config(Sensor, dgtl1,  bitch_lasagna,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  urf,            sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		writeDebugStreamLine("%d", SensorValue[urf]);
		if (20 <= SensorValue[urf] <= 25) {
			turnLEDOn(bitch_lasagna);
		}
		turnLEDOff(bitch_lasagna);
	}
}
