#pragma config(Sensor, dgtl1,  butt,           sensorTouch)
#pragma config(Motor,  port1,           plunge,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		if (SensorValue[butt] == 1) {
			motor[plunge] = -127;
		}	else {
			motor[plunge] = 0;
		}
	}
}
