#pragma config(Motor,  port2,           flywheel,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while (true) {
		if (vexRT[Btn5U] == 1) {
			startMotor(flywheel, 127);
		}	else {
			stopMotor(flywheel);
		}
	}
}
