#pragma config(Sensor, dgtl1,  butt1,          sensorTouch)
#pragma config(Sensor, dgtl2,  butt2,          sensorTouch)
#pragma config(Motor,  port3,           liftleft,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftright,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void startLift(int speed){
	startMotor(liftleft, speed);
	startMotor(liftright, speed*-1);
}

void stopLift(){
	stopMotor(liftleft);
	stopMotor(liftright);
}

task main()
{
	while (true) {
		if (SensorValue[butt1] == 1 ){
			startLift(127);
		} else if (SensorValue[butt2] ==  1) {
			startLift(-127);
		} else {
			stopLift();
		}
	}
}
