#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  jumper1,        sensorTouch)
#pragma config(Sensor, dgtl2,  jumper2,        sensorTouch)
#pragma config(Motor,  port2,           ne_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           se_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           nw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           sw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           manipulator,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 127;

// calibrate variables below
float timepercell = 775;
float timeperhalfturn = 375;

void turnLeft(int turns) {
	motor[ne_motor] = -1 * speed;
	motor[se_motor] = -1 * speed;
	motor[nw_motor]= -1 * speed;
	motor[sw_motor] = -1 * speed;
	delay(turns * timeperhalfturn);
	motor[ne_motor] = 0;
	motor[se_motor] = 0;
	motor[nw_motor]= 0;
	motor[sw_motor] = 0;
}

void turnRight(int turns) {
	motor[ne_motor] = speed;
	motor[se_motor] = speed;
	motor[nw_motor]= speed;
	motor[sw_motor] = speed;
	delay(turns * timeperhalfturn);
	motor[ne_motor] = 0;
	motor[se_motor] = 0;
	motor[nw_motor]= 0;
	motor[sw_motor] = 0;
}

void go(float cells){
	motor[ne_motor] = -1 * speed;
	motor[se_motor] = -1 * speed;
	motor[nw_motor]= speed;
	motor[sw_motor] = speed;
	delay(cells * timepercell);
	motor[ne_motor] = 0;
	motor[se_motor] = 0;
	motor[nw_motor]= 0;
	motor[sw_motor] = 0;
}

void liftup(float time) {
	startMotor(lift_left, speed*-1);
	startMotor(lift_right, speed);
	delay(time);
	stopMotor(lift_left);
	stopMotor(lift_right);
}

void liftdown(float time) {
	startMotor(lift_left, speed);
	startMotor(lift_right, speed*-1);
	delay(time);
	stopMotor(lift_left);
	stopMotor(lift_right);
}

void manip(float time){
	startMotor(manipulator, speed);
	delay(time);
	stopMotor(manipulator);
}

void manipr(float time) {
	startMotor(manipulator, -1*speed);
	delay(time);
	stopMotor(manipulator);
}

task main() {
	while (true){
		if (SensorValue[jumper1] == 1){ // drive onto platform
			go(1.5);
			turnLeft(2);
			go(2);
		} else if (SensorValue[jumper2] == 1) { // diagnostic
			go(1);
			delay(2000);
			turnLeft(2);
			turnRight(2);
			delay(2000);
			go(2);
		}
	}
}
