#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
WORLD RECORD: 1521 pts - Alan Luo
*/

int gameState = 2;

int player = 0;
int score = 0;
int lives = 3;
char playerChar = '$';

int eLn[16] = {0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};
int ePos[16] = {15, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

int mechDelay = 500;

void stopAll() {
	gameState = 0;
}

task watchButtons() {
	int cachedButton = nLCDButtons;
	while (true) {
			if (nLCDButtons == 1) {
				player = 0;
			} else if (nLCDButtons == 2) {
				player = 1;
			}
			if (gameState == 2) {
				if (nLCDButtons == 4) {
					gameState = 1;
				}
			}
			cachedButton = nLCDButtons;
	}
}

task render() {
	while (true) {
		char row[2][16];

		row[player][0] = playerChar;
		row[1 - player][0] = ' ';

		for (int i = 1; i < 16; i++){
			row[player][i] = ' ';
			row[1 - player][i] = ' ';
		}

		for (int i = 0; i < 16; i++){
			int line = eLn[i];
			int pos = ePos[i];

			if (line <= -1 || pos <= -1) {
				continue;
			}

			row[line][pos] = '<';
		}
		row[0][15] = lives + '0';

		string ln0 = "";
		string ln1 = "";

		for (int c1 = 0; c1 < 16; c1++) {
			ln0 += row[0][c1];
		}

		for (int c2 = 0; c2 < 16; c2++) {
			ln1 += row[1][c2];
		}

		displayLCDString(0, 0, ln0);
		displayLCDString(1, 0, ln1);
	}
}

task manageGameMechanics() {
	int loops = 0;
	while (true) {
		delay(mechDelay);
		if (lives == 0) {
			stopAll();
		}
		for (int i = 0; i < 16; i++) {
			ePos[i] -= 1;
			if (eLn[i] == player && ePos[i] == 0) {
					lives--;
			}
		}
		score++;
		if (loops % 2 == 0) {
			int where = 0;
			for (int i = 0; i < 16; i++){
				if (eLn[i] <= -1 || ePos[i] <= -1) {
					where = i;
					break;
				}
			}

			eLn[where] = random(1);
			ePos[where] = 15;
		}
		if (loops % 10 == 0 && mechDelay > 220) {
			writeDebugStream("%d\n", mechDelay);
			mechDelay -= 20;
		}
		loops += 1;
	}
}

task main() {
	bLCDBacklight = true;

	startTask(watchButtons);

	while (gameState == 2) {
			displayLCDCenteredString(0, "ShittyLCDGame");
			displayLCDString(1, 0, "          Start ")
	}

	startTask(render);
	startTask(manageGameMechanics);

	clearLCDLine(0);
	clearLCDLine(1);

	while(true){
		if (gameState == 0) {
			stopTask(render);
			stopTask(manageGameMechanics);

			clearLCDLine(0);
			clearLCDLine(1);

			string scoreString;
			sprintf(scoreString, "Score: %d", score);

			displayLCDCenteredString(0, "Game over!");
			displayLCDCenteredString(1, scoreString);
		}
	}
}
