#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  debugButt,      sensorTouch)
#pragma config(Sensor, dgtl2,  debugButt2,     sensorTouch)
#pragma config(Sensor, dgtl10, led_red,        sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, led_yellow,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, led_green,      sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           flipper,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           sw_motor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           nw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shooter_left,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           se_motor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           ne_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backup_intake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          shooter_right, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
== BUTTON LAYOUT ==
RIGHT & LEFT JOYSTICKS -> drive train (left side & right side)
5U -> plunger control
6U -> Intake Up
6D -> Intake Down
5D -> Flipper
7L -> Flash LEDs
*/

task flashLED() {
	turnLEDOn(led_red);
	delay(500);
	turnLEDOff(led_red);
	turnLEDOn(led_yellow);
	delay(500);
	turnLEDOff(led_yellow);
	turnLEDOn(led_green);
	delay(500);
	turnLEDOff(led_green);
}

task main() {
	while(true){
		// drive train
		motor[nw_motor] = vexRT[Ch3];
		motor[sw_motor] = vexRT[Ch3];

		motor[ne_motor]= -1 * vexRT[Ch2];
		motor[se_motor] = -1 * vexRT[Ch2];

		// shooter control
		if (vexRT[Btn5U] == 1) {
			motor[shooter_left] = -127;
			motor[shooter_right] = 127;
		} else {
			motor[shooter_left] = 0;
			motor[shooter_right] = 0;
		}

		// intake control
		if (vexRT[Btn6D] == 1) {
			motor[intake] = 127;
		} else if (vexRT[Btn6U] == 1){
			motor[intake] = -127;
		} else {
			motor[intake] = 0;
		}

		// flipper control
		if (vexRT[Btn8L] == 1) {
			motor[flipper] = -127;
		} else if (vexRT[Btn8D]){
			motor[flipper] = 127;
		} else {
			motor[flipper] = 0;
		}

		// led control
		if (vexRT[Btn7L] == 1) {
			startTask(flashLED);
		}
	}
}
