#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  debugButt,      sensorTouch)
#pragma config(Sensor, dgtl2,  debugButt2,     sensorTouch)
#pragma config(Motor,  port2,           ne_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           se_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           nw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           sw_motor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           manipulator,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           transmanip,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
== BUTTON LAYOUT ==
RIGHT & LEFT JOYSTICKS -> drive train (left side & right side)
6U & 6D -> lift system control (up & down)
5U & 5D -> manipulator control (right & left)
8U & 8D -> move manipulator (up & down)
*/

// 0 = single joystick, 1 = double joystick
int controlMode = 1;

void startLift(int speed){
	startMotor(lift_left, speed*-1);
	startMotor(lift_right, speed);
}

void stopLift(){
	stopMotor(lift_left);
	stopMotor(lift_right);
}

task main() {
	while(true){
		if (controlMode == 0) {
			motor[ne_motor] = -1 * (vexRT[Ch2] - vexRT[Ch1])/2;
			motor[se_motor] = -1 * (vexRT[Ch2] - vexRT[Ch1])/2;

			motor[nw_motor]= (vexRT[Ch2] + vexRT[Ch1])/2;
			motor[sw_motor] = (vexRT[Ch2] + vexRT[Ch1])/2;
		} else if (controlMode == 1) {
			motor[ne_motor] = -1 * vexRT[Ch2];
			motor[se_motor] = -1 * vexRT[Ch2];

			motor[nw_motor]= vexRT[Ch3];
			motor[sw_motor] = vexRT[Ch3];
		}

		if (vexRT[Btn6U] == 1 ){
			startLift(127);
		} else if (vexRT[Btn6D] ==  1) {
			startLift(-50);
		} else {
			stopLift();
		}


		if (vexRT[Btn5U] == 1) {
			startMotor(manipulator, 127);
		} else if (vexRT[Btn5D] == 1) {
			startMotor(manipulator, -127);
		} else {
			stopMotor(manipulator);
		}
	}
}
